lista = c('1. As pessoas se apoiam umas às outras nesta unidade',
          '2. Temos pessoas suficientes para lidar com o volume de trabalho',
          '3. Quando há muito trabalho a ser feito e rapidamente, trabalhamos juntos em equipe para realizar a tarefa',
          '4. Nesta unidade, as pessoas se tratam com respeito',
          '5. Os funcionários desta unidade trabalham mais horas do que o recomendado no atendimento a pacientes',
          '6. Estamos ativamente buscando melhorias para a segurança do paciente',
          '7. Utilizamos mais funcionários temporários do que o recomendado no atendimento a paciente',
          '8. Os funcionários sentem que seus erros são usados contra eles',
          '9. Erros que ocorreram levaram a mudanças positivas nesta unidade',
          '10. É apenas por acaso que erros mais sérios não acontecem por aqui',
          '11. Quando uma área nesta unidade fica muito movimentada, as demais ajudam',
          '12. Quando um evento é notificado, sentimos que o foco se concentra no indivíduo, e não no problema',
          '13. Quando fazemos mudanças para melhorar a segurança do paciente, nós avaliamos sua efetividade',
          '14. Trabalhamos “em modo de crise”, tentando fazer coisas demais, rápido demais',
          '15. A segurança do paciente nunca é sacrificada em prol de se trabalhar mais',
          '16. Os funcionários se preocupam que seus erros sejam registrados em seu arquivo funcional',
          '17. Temos problemas com a segurança do paciente nesta unidade',
          '18. Nossos procedimentos e sistemas são bons para impedir que os erros aconteçam',
          '19. Meu supervisor/gerente elogia quando vê um trabalho feito de acordo com os procedimentos estabelecidos para a segurança do paciente.',
          '20. Meu supervisor/gerente considera seriamente as sugestões dos funcionários para melhorar a segurança do paciente',
          '21. Sempre que a pressão aumenta, meu supervisor/gerente quer que trabalhemos mais rápido, mesmo que isto signifique tomar atalhos',
          '22. Meu supervisor/gerente ignora problemas recorrentes na segurança do paciente',
          '23. Recebemos feedback das mudanças implementadas com base nos eventos notificados',
          '24. Os funcionários falam voluntariamente se vêem algo que possa afetar negativamente o atendimento aos pacientes',
          '25. Somos informados sobre os erros que acontecem nesta unidade',
          '26. Os funcionários sentem-se à vontade para questionar decisões ou ações dos que têm mais autoridade',
          '27. Nesta unidade, discutimos maneiras de impedir que os erros tornem a acontecer',
          '28. Os funcionários têm receio de perguntar quando algo não parece certo',
          '29. Quando acontece um erro, mas ele é identificado e corrigido antes de afetar o paciente, com que frequência é notificado?',
          '30. Quando acontece um erro, mas que não tem potencial de dano ao paciente, com que frequência é notificado?',
          '31. Quando acontece um erro que poderia prejudicar o paciente, mas isto não ocorreu, com que frequência é notificado?',
          #'Por favor, dê uma nota geral para a segurança do paciente em sua área/unidade de trabalho hospitalar.',
          '32. A administração do hospital cria um ambiente de trabalho que promove a segurança do paciente',
          '33. As unidades hospitalares não se coordenam bem entre si.',
          '34. Coisas "escapam por entre os dedos” quando os pacientes são transferidos de uma unidade para outra',
          '35. Existe uma boa cooperação entre as unidades hospitalares que precisam trabalhar juntas',
          '36. Importantes informações sobre a assistência se perdem durante as mudanças de turno',
          '37. Muitas vezes é desagradável trabalhar unidades com funcionários de outras unidades do hospital',
          '38. Os problemas com frequência ocorrem na troca de informações entre as unidades do hospital',
          '39. As ações da administração do hospital mostram que a segurança do paciente é uma prioridade máxima',
          '40. A administração do hospital parece se interessar pela segurança do paciente apenas quando acontece um evento adverso',
          '41. As unidades do hospital trabalham bem juntas para prestar o melhor atendimento aos pacientes',
          '42. As mudanças de turno são problemáticas para os pacientes deste Hospital')

colunas_adicionais <- c('Abertura de comunicação', 'Feedback e comunicação sobre erros', 'Frequência de eventos relatados',
                        'Apoio de gestão hospitalar para segurança do paciente', 'Trabalho em equipe entre as unidades hospitalares',
                        'Trabalho em equipe no âmbito das unidades', 'Transferências internas e passagens de plantão',
                        'Aprendizado organizacional - melhoria contínua', 'Expectativas de promoção da segurança dos supervisores e gerentes',
                        'Percepção gerais sobre segurança', 'Respostas não punitivas aos erros', 'Staffing')

lista = c(lista, colunas_adicionais)

colunas_adicionais = c('SEÇÃO G2: Notificou algum evento nos ultimos 12 meses',
                       'SEÇÃO G: Número de Eventos Notificados  Nos últimos 12 meses, quantas notificações de evento você preencheu e enviou?_0. Nenhuma notificações de eventos',
                       'SEÇÃO G: Número de Eventos Notificados  Nos últimos 12 meses, quantas notificações de evento você preencheu e enviou?_1. 1 a 2 notificações de eventos',
                       'SEÇÃO G: Número de Eventos Notificados  Nos últimos 12 meses, quantas notificações de evento você preencheu e enviou?_2. 3 a 5 notificações de eventos',
                       'SEÇÃO G: Número de Eventos Notificados  Nos últimos 12 meses, quantas notificações de evento você preencheu e enviou?_3. 6 a 10 notificações de eventos',
                       'SEÇÃO G: Número de Eventos Notificados  Nos últimos 12 meses, quantas notificações de evento você preencheu e enviou?_4. 11 a 20 notificações de eventos',
                       'SEÇÃO G: Número de Eventos Notificados  Nos últimos 12 meses, quantas notificações de evento você preencheu e enviou?_5. 21 notificações de eventos ou mais',
                       'SEÇÃO H: 3.2 Trabalha mais que 40horas semanais',
                       'SEÇÃO H: 3.2 Trabalha mais que 60horas semanais',
                       'SEÇÃO H: 3.2 Trabalha mais que 80horas semanais',
                       'Por favor, dê uma nota geral para a segurança do paciente em sua área/unidade de trabalho hospitalar._Excelente',
                       'Por favor, dê uma nota geral para a segurança do paciente em sua área/unidade de trabalho hospitalar._Muito boa',
                       'Por favor, dê uma nota geral para a segurança do paciente em sua área/unidade de trabalho hospitalar._Muito ruim',
                       'Por favor, dê uma nota geral para a segurança do paciente em sua área/unidade de trabalho hospitalar._Ruim',
                       'Por favor, dê uma nota geral para a segurança do paciente em sua área/unidade de trabalho hospitalar._Satisfatória',
                       'Nota Geral == Satisfatoria ?', 'Nota Geral == Boa ?',
                       'SEÇÃO H: 1.2 trabalha a mais de 1 ano no hospital?',
                       'SEÇÃO H: 1.3 trabalha a mais de 5 anos no hospital?',
                       'SEÇÃO H: 1. Há quanto tempo você trabalha neste hospital?_0. Menos de 1 ano',
                       'SEÇÃO H: 1. Há quanto tempo você trabalha neste hospital?_1. 1 a 5 anos',
                       'SEÇÃO H: 1. Há quanto tempo você trabalha neste hospital?_2. 6 a 10 anos',
                       'SEÇÃO H: 1. Há quanto tempo você trabalha neste hospital?_3. 11 a 15 anos',
                       'SEÇÃO H: 1. Há quanto tempo você trabalha neste hospital?_4. 16 a 20 anos',
                       'SEÇÃO H: 1. Há quanto tempo você trabalha neste hospital?_5. 21 anos ou mais',
                       '6. Há quanto tempo você trabalha em sua profissão ou especialização atual?_0. Menos de 1 ano',
                       '6. Há quanto tempo você trabalha em sua profissão ou especialização atual?_1. 1 a 5 anos',
                       '6. Há quanto tempo você trabalha em sua profissão ou especialização atual?_2. 6 a 10 anos',
                       '6. Há quanto tempo você trabalha em sua profissão ou especialização atual?_3. 11 a 15 anos',
                       '6. Há quanto tempo você trabalha em sua profissão ou especialização atual?_4. 16 a 20 anos',
                       '6. Há quanto tempo você trabalha em sua profissão ou especialização atual?_5. 21 anos ou mais')

lista = c(lista, colunas_adicionais)